language: node_js
node_js: stable

branches:
  only:
    - master

cache:
  apt: true
  yarn: false
  directories:
    - node_modules

before_install:
- git config --global user.name "Boris Zhao"
- git config --global user.email "boris1993@126.com"
- npm install -g hexo-cli

install:
- npm i

script:
- hexo clean
- hexo generate

after_success:
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml
- hexo deploy
